name: tienda_online_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  cloud_firestore: ^4.17.2
  firebase_auth: ^4.19.4
  firebase_core: ^2.30.1
  firebase_ui_auth: ^1.14.0
  flutter:
    sdk: flutter
  flutter_animated_button: ^2.0.3
  intl: ^0.18.1
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  fonts:
    - family: RedHatDisplay
      fonts:
        - asset: assets/fonts/red_hat_display/red-hat-display-latin-300-normal.ttf
        - asset: assets/fonts/red_hat_display/red-hat-display-latin-400-normal.ttf
        - asset: assets/fonts/red_hat_display/red-hat-display-latin-500-normal.ttf
        - asset: assets/fonts/red_hat_display/red-hat-display-latin-600-normal.ttf
        - asset: assets/fonts/red_hat_display/red-hat-display-latin-700-normal.ttf

  assets:
    - assets/images/logo.png
    - assets/images/bg.png
    - assets/images/mercado.png
    - assets/images/aseo.png
    - assets/images/electrodomesticos.png
    - assets/images/muebles.jpg
    - assets/images/Aseo/detergente.png
    - assets/images/Aseo/cepillo.png
    - assets/images/Electrodomesticos/lavadora.png
    - assets/images/Electrodomesticos/nevera.png
    - assets/images/Muebles/escritorio.png
    - assets/images/Muebles/sofa.png
    - assets/images/Mercado/arroz.png
    - assets/images/Mercado/uvas.png

  uses-material-design: true
