name: tienda_online_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_animated_button: ^2.0.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  fonts:
    - family: RedHatDisplay
      fonts:
        - asset: assets/fonts/red_hat_display/red-hat-display-latin-300-normal.ttf
        - asset: assets/fonts/red_hat_display/red-hat-display-latin-400-normal.ttf
        - asset: assets/fonts/red_hat_display/red-hat-display-latin-500-normal.ttf
        - asset: assets/fonts/red_hat_display/red-hat-display-latin-600-normal.ttf
        - asset: assets/fonts/red_hat_display/red-hat-display-latin-700-normal.ttf

  assets:
    - assets/images/logo.png
    - assets/images/bg.png
  uses-material-design: true
